### ISSUE TITLE
Ramowy plan działania na warsztat 00_Basics

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/RLadies#1]

**Comment by MarcinKosinski** [comment]
@potockan @olgamie @agnieszka_tom

Wrzuciłem w tym commitcie https://github.com/mi2-warsaw/RLadies/commit/56a1e2fcb31bbe0a0a6874550a9b936dcd7cb186 pierwsze 30 minut warsztatu. To są potrzebne rzęczy, tak by uniknąć zbędnych pytań i zamieszania w trakcie warsztatu. To są naturalne rzęczy, nad którymi zastanawiają się początkujący użytkownicy kiedy mają pierwszy kontakt z R. Te pytania będą nurtować uczestników przez cały warsztat, gdybyśmy je pominęli i od razu zaczęli analizować dane, dlatego warto na nie od razu odpowiedzieć.

Należy pamiętać, że niektórze nie dość, że nigdy nie pracowali z R, to tym bardziej mogą nie wiedzieć nic o programowaniu a możliwe, że i nie spotkali się wcześniej z pojęciem `analiza danych` [wyjaśnienie tego pojęcia nie jest ujęte w naszym warsztacie, ale feel free]. To wszystko trzeba wyjaśnić i zmotywować do działania : )

Ja się raczej będę trzymał tego planu warsztatu, ale wy oczywiście nie musicie. Próbowałem wielu różnych podejść do warsztatów w kilku środowiskach i ostatecznie oparłem plan na pytaniach od użytkowników padających w trakcie warsztatu.

**Comment by MarcinKosinski** [comment]
@AgnieszkaTomczyk

**Comment by MarcinKosinski** [comment]
W pliku https://github.com/mi2-warsaw/RLadies/blob/master/00_Basics/00_ramowy_plan.Rmd#wst%C4%99pna-analiza-poznawcza-danych dodałem sekcję ze `Wstępna analizą poznawczą danych` .
Jest tam omówione kilka funkcji dplyr'a i są tam 2 proste zadania. Myślę, że zajmie to kolejne 30 minut.

@olgamie @potockan @AgnieszkaTomczyk Myślicie, że w 3ciej części warsztatu lepiej przedstawić jak konstruować funkcje (może też ewentualnie pętle) i instrukcje warunkowe (if/else), czy lepiej funkcje agregujące / summarise czy summarise w grupach i proste wykresy - boxplot/hist ?

**Comment by potockan** [comment]
@MarcinKosinski myślę, że to zależy od grupy. Przeglądałam zgłoszenia i jest część, która używała SPSS czy SAS, więc pojęcie funkcji, pętli i instrukcji warunkowej może być dla nich banalne. Ale sporo osób wpisała tylko Excela, więc o ile if-a mogą znać, to raczej pętli i funkcji już nie za bardzo.
Ja myślałam, że uda się pokazać wszystkie te rzeczy, tylko nie wiem jak się wyrobimy czasowo :D

**Comment by potockan** [comment]
@MarcinKosinski Moje uwagi co do materiałów:
1. Przy wczytywaniu danych podajesz, że jest używany pakiet `readr` (`read_csv`). U mnie wczytuje się przy użyciu bazowego`R` (`read.csv`) i podejrzewam, że tak będzie u większości, bo większość nie ma zainstalowanego pakietu `readr`.
2. Minimalna i maksymalna cena dostawy są czasem zamienione - pierwszy rekord ma, odpowiednio, 11 i 8.6 jako min. i max. Ale to chyba wina danych, a nie pobierania.
3. Zastanawiam się, czy jest sens pokazywać im różnicę między bazowym `R`-em a np. `dplyr`-em, skoro nic jeszcze o `R` nie wiedzą - nie namiesza im to w głowach?
4. Zadanie 2. rozbiłabym na dwa zadania, a między nimi pokazała, że można przekształcać kolumny.
5. Odpowiadając na Twoje pytanie: po przeczytaniu Twoich materiałów naturalne wydaje się, że na koniec zrobimy wizualizację wyników, np. kto ile ma do sprzedania par, czy coś w tym stylu. I tutaj bym wprowadziła `ggplota`, bo bazowy `R` to masakra.

**Comment by potockan** [comment]
1. Brakuje pokazania `summarise`, żeby zrobić pierwszą część zadania 2.

**Comment by MarcinKosinski** [comment]
@potockan  faktycznie. Dzięki za uwagi :)!

Dodam `summarise` i `group_by` jako kolejny przykład.

co do 1. to musisz zainstalować najnowszą wersję RStudio - teraz `tibble` to standard a `data.frame` to przykra pozostałość niestety ;/ - tutaj można zobaczyć jaka jest różnica między nimi a `data.frame` https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html - może też dodać przykład tego jak tworzyć te obiekty i jak tworzyć `data.frame`
1. to od razu pokazuje, że czasem są głupoty w danych i trzeba mieć tego świadomość - nie wiem jak to się stało przy pobieraniu.
2. Czeba czeba, teraz wszędzie jest tibble a ja podstawowego R już nie pamiętam
3. good point
4. dobra to lecimy z wykresiorami

6.7.8.9.10.11 - trzeba powiedzieć, że jeszcze nie wiedzą jak zrobić funkcję, napisać ifa, czy nie widziały listy : P i że muszą przyjść na następny warsztat z Basics_2!

**Comment by olgamie** [comment]
@MarcinKosinski to jest w  nowej wersji RStudio czy w Developerskiej? W Deweloperskiej tak, a czy w tej pierwszej?

**Comment by potockan** [comment]
Właśnie zainstalowałam najnowsze RStudio i dalej czyta bazowym R-em :) Więc chyba tylko Dev.

**Comment by MarcinKosinski** [comment]
Ja mam taką

![rstudio](https://cloud.githubusercontent.com/assets/6773454/19472781/f3b901e2-9528-11e6-856b-1b9ea9725d0e.png)

**Comment by MarcinKosinski** [comment]
Czekajcie, zrobie reinstalkę : P

**Comment by olgamie** [comment]
Ja bym proponowała zrobić prosty wykres na sam koniec, może być w basie, a potem zainsyalowała plotly i pokazała im prosty interaktywny barchart

**Comment by potockan** [comment]
Ja mam wersję Version 0.99.903, co na stronie RStudio jest jako najnowsza.
![screenshot from 2016-10-18 11-51-38](https://cloud.githubusercontent.com/assets/6773442/19472855/49417496-9529-11e6-9294-833b1c8a291d.png)

**Comment by olgamie** [comment]
@MarcinKosinski warto jeszcze poświęcić chwilę na umówienie instalacji pakietów - konsola a okno w RStudio, podpowiadanie przez RStudio oraz instalowanie kilku jednocześnie

**Comment by AgnieszkaTomczyk** [comment]
Wydaje mi się,  że nie zdążymy tyle zrobić.  Dużo ważniejsze jest instalowanie pakietów,  niż ładny wykres. Wykres można im zrobić w basie i np. Wspomnieć o ładniejszych.  I tak mają ogromne materiału. Pamiętajcie,  że są na poziomie 0.

**Comment by potockan** [comment]
Dobra uwaga @AgnieszkaTomczyk :)

**Comment by MarcinKosinski** [comment]
- To wykres już na dokładkę. Lepiej mieć jedną linijkę i się z nią nie
  wyrobić niż jej nie mieć :) proponuję `hist` na cenach :)
- Faktycznie w wersji RELEASE wczytywanie jest przez read.csv a w
  DEVELOPERSKIEJ przez readr:read_csv :) no to zmodyfikuję lekko warsztat,
  żeby może nie było za dużo tego tibbla (tzn nie bedzie go przy wczytywaniu
  danych, ale pojawi sie w pierwszym momencie gdy uruchomimy dplyr'a)
- Myślę, że póki co mamy warsztatu tak na 75 minut. Gdyby dorzucić jeszcze
  punkt o instalacji i włączaniu pakietów (przez panel i ręcznie) to możemy
  dobić do 82. Wykresios i summarise z group_by i mamy 90 minut :) Dorzucę
  dziś w ciągu dnia finalne materiały, uwzględniające Wasze uwagi :)

dzięki za komcie

**Comment by MarcinKosinski** [comment]
- jeszcze trzeba pokazać jak pobrać materiały i je włączyć
- wejście na stronę http://github.com/mi2-warsaw/RLadies
- kliknięcie zielonego guzika `downloac or clone`
- pobranie zipa
- wyeksportowanie na Windowsie (rozpakowanie)
- kliknięcie 2 razy na `projekt`

W dniu 18 października 2016 12:30 użytkownik Marcin Kosiński <
m.p.kosinski@gmail.com> napisał:

> - To wykres już na dokładkę. Lepiej mieć jedną linijkę i się z nią nie
>   wyrobić niż jej nie mieć :) proponuję `hist` na cenach :)
> - Faktycznie w wersji RELEASE wczytywanie jest przez read.csv a w
>   DEVELOPERSKIEJ przez readr:read_csv :) no to zmodyfikuję lekko warsztat,
>   żeby może nie było za dużo tego tibbla (tzn nie bedzie go przy wczytywaniu
>   danych, ale pojawi sie w pierwszym momencie gdy uruchomimy dplyr'a)
> - Myślę, że póki co mamy warsztatu tak na 75 minut. Gdyby dorzucić jeszcze
>   punkt o instalacji i włączaniu pakietów (przez panel i ręcznie) to możemy
>   dobić do 82. Wykresios i summarise z group_by i mamy 90 minut :) Dorzucę
>   dziś w ciągu dnia finalne materiały, uwzględniające Wasze uwagi :)
> 
> dzięki za komcie

**Comment by olgamie** [comment]
@MarcinKosinski jeśli kod 
filter(oferty_informacje_low, !grepl('zapiętki|wkładki', oferty_informacje_low$tytul_lower)) -> oferty_informacje_buty 

ma na celu odfiltrowanie butów to jest niewyarczajace jest wywalenie tylko zapietek i wkladek dochodza tez np. fleki :) i to wplywa na zadanie nr 1 ;) => gdzie minimalna cena na tej ramce to cena dla flekow

**Comment by MarcinKosinski** [comment]
Przeczytaj najpierw cale materialy : )

**Comment by potockan** [comment]
@olgamie na tym polega to zadanie. Podaje moje rozwiązanie tego zadania, jeśli ktoś chce:

```
# zad. 1
inne_niz_buty <- grepl('flek|sznurówki|sznurowadła|farba|lakier|pasta|krem|dezodorant|spray|szczotka|podkładki|pianki', 
                       oferty_informacje_buty$tytul_lower)
# warto dodać, że nie wrzucamy np. "sznurow", 
# bo czasem w ofercie jest "sznurowane botki...", 
# a to nam usunie też ofertę butów

table(inne_niz_buty)

oferty_informacje_buty[inne_niz_buty, ]

oferty_informacje_buty[!inne_niz_buty, ]

filter(oferty_informacje_buty, !inne_niz_buty) -> oferty_informacje_buty2

head
  select(
    arrange(oferty_informacje_buty2, cena),
    cena, tytul_lower
  ), 
100)
```

**Comment by MarcinKosinski** [comment]
Zdanie 

> Dalej mamy oferty, które nie dotyczą butów, lecz dodatków do nich. W parach, znaleźć najtańszą ofertę z butami.

Oznacza, że wiemy, że ten przykład nie wyfiltorwał wszystkiego i zadaniem jest to, że trzeba je wyfiltorwać w całości.

Chodzi o to, że ja pokazuje jak wyfiltorwać część ofert, a zadanie 1 polega na tym, żeby wyfiltrować wszystko co nie jest butem (from @potockan )

``` R
inne_niz_buty <- grepl('flek|sznurówki|sznurowadła|farba|lakier|pasta|krem|dezodorant|spray|szczotka|podkładki|pianki', 
                       oferty_informacje_buty$tytul_lower)
table(inne_niz_buty)

oferty_informacje_buty[inne_niz_buty, ]

oferty_informacje_buty[!inne_niz_buty, ]

filter(oferty_informacje_buty, !inne_niz_buty) -> oferty_informacje_buty2

head
  select(
    arrange(oferty_informacje_buty2, cena),
    cena, tytul_lower
  ), 
100)
```

**Comment by olgamie** [comment]
@MarcinKosinski @potockan dzieki z komenatzry zrozumialma ze to juz sa same buty. Moim zdaniem to zadanie jest za trudne dla osoby, ktora nigdy nie miala doczyniania z R.

**Comment by MarcinKosinski** [comment]
Za mało wierzycie w przyszłość tego kraju (ludzi) : )

**Comment by potockan** [comment]
To najwyżej zrobimy to zadanie wspólnie (prawie na pewno), a potem zrobimy jakiś prosty wykres, już bez mutate i bez summarise (albo tylko jedno pokażemy).

**Comment by olgamie** [comment]
Ja bym to podzieliła na kilka zadan => na tej ramce ofety_informacje_buty znajdz najtansza oferte? Jaka to jest cena? Czy jest to cena butów? Jakiwgo produktu dotyczy? i Potem wyfiltrowac do butów :)

**Comment by MarcinKosinski** [comment]
Podoba mi się @olga to co proponujesz.
Zaraz wrzucę treść zedytowaną przeze mnie, na której będziesz mogła nanieść poprawki.

PS początkowe zadanie wydawało się ciężkie bo nie kojarzyłyście funkcji `grepl` ? : P toż to taka przedzskolna funkcja

**Comment by olgamie** [comment]
czemu piszesz w liczbnie mnogiej? @potockan sobie poradziła :D to tylko ja ;)

**Comment by MarcinKosinski** [comment]
No bo się zastanawiam, czy zadanie było ciężkie, czy po prostu nie znałaś funkcji grepl

**Comment by olgamie** [comment]
nie po prostu załozyłam ze ramka ofety_info_buty zawiera juz tylko buty

**Comment by MarcinKosinski** [comment]
Dobra, ja póki co nie wprowadzam zmian.

Możecie zobaczyć jakie zmiany wprowadziłem po Waszych uwagach (https://github.com/mi2-warsaw/RLadies/commit/e892ac86f5311aa31ed717037d96f35a144c2a39) a o których zapomniałem.

Olga rozbijesz moje zadania wg Twojego pomysłu?

**Comment by olgamie** [comment]
wrzuciłam wczoraj wieczorem dwa skrypty do nowego brancha. Dodałam kilka podstawowych rzeczy z R o ktorych chce powiedziec czyli czym jest wektor co to jest lista itd. Oraz wyciagnełam do drugiego pliku z markdowna Twoj kod @MarcinKosinski. Dodałam przy tym jeszcze kilka funkcji z dplyra. 

Zmieniłam też trochę zadania. Moim zdaniem zadanie 1 nie jest dobre na warsztat, ponieważ ciężko będzie napisać wyrażenie do wyfiltrowania tylko butów. Np. w tym co napisała Natalia dalej są prawidła, jakieś tłuszcze ochronne do butów itd... Moim zdaniem takie zadanie wprowadzi tylko zamieszanie, bo żadna z nich nie napisze tej funkcji tak, żeby zostały tylko buty. Inną kwestią jest to, że może znajdą cenę 8.99. W każdym razie to jest moje zdanie, dlatego zrobiłam 2gi skrypt.

Jedyne co to @MarcinKosinski trzeba pozamykać te issusy przed warsztatem :)

**Comment by MarcinKosinski** [comment]
A do którego brancha? Bo zrobiłaś już póki co 2 :P
Swoją drogą commitująć można dodać do wiadomości commita `#1` aby umieścić te commity w drzewie tej dyskusji na githubie. Przykład `poprawki zadań w #1`

**Comment by MarcinKosinski** [comment]
jeżeli branch `scrape_allegro` to ten skrypt jest bardzo dobry: https://github.com/mi2-warsaw/RLadies/blob/scrape_allegro/00_Basics/script.R

Jeżeli chodzi o dodatkowe materiały do grupy `6` to lepiej zrobić dodatkowy folder w master branchu niż dodatkowy branch :)

**Comment by olgamie** [comment]
sorki troche zamotałam, bo zrobiłam tez poprawki do scrapera i zapommnaiłam
wyjść z mastera. zaraz posprzatam

2016-10-19 12:42 GMT+02:00 Marcin Kosiński notifications@github.com:

**Comment by MarcinKosinski** [comment]
Jak dla mnie jest już wszystko co powinniśmy mieć : ) ewentualnie zawsze jak zostanie 5-10 minut to można pokazać jakąś galerię projektów Rowych w necie. 
@olgamie wg mnie mozęsz mergować branche i zamknąć ten temat
