### ISSUE TITLE
materiały na 1 warsztaty 20.10.2016

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/RLadies#2]
@mi2-warsaw/rladiesworkshoptutors myślicie, że moglibyśmy wydrukować użytkownikom podstawowych warsztatów pewną ściągawkę z RStudio?

https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf

do ggplot2 też taka jest https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf

**Comment by olgamie** [comment]
@MarcinKosinski jesli wystarczt finansow to tak. ja sie tym zajme

**Comment by AgnieszkaTomczyk** [comment]
[Pytanie dot. pośrednio materiałów, więc zostańmy w wątku.] 
- Czy uczestniczki mają przekazane instrukcje do instalacji środowiska?
- Jak będzie na miejscu z dostępem do sieci? Czy mamy dla nich jakieś łącze bez konieczności rejestracji tej na MiNI?
  Jeżeli jakoś dubluję zagadnienia, to przepraszam. Za dużo wątków już było na mailu. :)

**Comment by MarcinKosinski** [comment]
Podobno poszedł mail do uczestników (ale nie z kopią do prowadzących) z
informacją jak przygotować się do warsztatów.
Mnie bardziej martwi czy ludzie wiedzą, że mają przynieść przedłużacze.

Co do sieci to nasz wydział lubi pokazywać, że w 21 wieku możliwe jest, że
na wydziale informatycznym nie ma dostępu do sieci WiFi i sieć orange traci
zasięg. Jednak staramy się uzyskać dostęp do WiFi.

W dniu 19 października 2016 06:53 użytkownik Agnieszka Tomczyk <
notifications@github.com> napisał:

**Comment by olgamie** [comment]
@mi2-warsaw/rladiesworkshoptutors tak wiedzą o instalacji R, RSTudio i pakietów dostały materiały od Przemka jak to zrobić. 

Właśnie poszła na meetup informacja, żeby zabrac przedłużacze. Dobrze będzie jeśli i wy będziecie miec chociaż jeden.

**Comment by MarcinKosinski** [comment]
To może jeszcze materiały z dplyra :P ?
https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
