### ISSUE TITLE
SER

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/RLadies#9]
Proponuję przenieść to repozytorium do repo SER na mi2 jako XX spotkanie
http://github.com/mi2-warsaw/SER

Łatwiej będzie je znaleźć, 
obecnie jest dużo drobnych repozytoriów na mi2 i utrudnia to znalezienie czegoś

**Comment by MarcinKosinski** [comment]
Ja proponuję w SER mi2 XX dać w readme link do tego repozytorium i oddzielać SER od R-Ladies żeby nie było to zbyt pomieszane
